export enum PageName {
  Home = "Hem",
  Dogs = "Hundar som söker hem",
  DogsAdopted = "Adopterade hundar",
  Adoption = "Adoption via Bff Strays",
  Requirements = "Krav på adoptörer",
  WorkEthics = "Vårt arbetssätt",
  About = "Om föreningen",
  Spain = "Situationen i Spanien",
  Myths = "Myter om gatuhundar",
  Donate = "Donera",
  RegisterInterest = "Intresseanmälan",
  Contact = "Kontakt",
  Diseases = "Sjukdomar",
}
